backend:
  name: github
  repo: robb-j/r0b-blog

media_folder: uploads

collections:
  - name: config
    label: Config
    files:
      - name: site
        label: Site
        preview: false
        editor: { preview: false }
        file: _data/site.json
        fields:
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: homeUrl, label: Home URL, widget: string }
          - { name: twitter, label: Twitter, widget: string }

  - name: posts
    label: Posts
    folder: post
    create: true
    identifier_field: title
    preview: false
    editor: { preview: false }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime, timeFormat: false }
      - { name: draft, label: Draft, widget: boolean }
      - { name: summary, label: Summary, widget: text }
      - { name: body, label: Body, widget: markdown, editorComponents: [] }
